name: Coenraad Dingemans Audio Productions
favicon: null
layout_spectrum: 0.3077
typography_spectrum: 1
title: Passionate audio engineering and production
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#281d19'
    - '#f0f2f1'
    - '#afa09b'
    - '#74686a'
    - '#813f1c'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
