name: Passionate Audio Productions
favicon: null
layout_spectrum: 0.75419
typography_spectrum: 0.63378
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Coenraad Dingemans Audio Productions
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#281d19'
    - '#f0f2f1'
    - '#afa09b'
    - '#74686a'
    - '#813f1c'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
